added changes

diff --git a/.github/actions/build/action.yml b/.github/actions/build/action.yml
--- a/.github/actions/build/action.yml
+++ b/.github/actions/build/action.yml
@@ -135,15 +135,22 @@ runs:
         vuln-type: 'os,library'
         scanners: 'vuln,secret,config'
 
-    - name: Upload SARIF artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: trivy-results
-        path: trivy-results.sarif
+    - name: Verify Trivy output
+      if: always()
+      run: |
+        echo "Checking if trivy-results.sarif exists..."
+        ls -l ${{ github.workspace }}/trivy-results.sarif || echo "Trivy output not found!"
 
 
-    - name: Checkout repository
-      uses: actions/checkout@v5    
+    # - name: Upload SARIF artifact
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: trivy-results
+    #     path: trivy-results.sarif
+
+
+    # - name: Checkout repository
+    #   uses: actions/checkout@v5    
 
     - name: Upload SARIF to target repository
       uses: github/codeql-action/upload-sarif@v3
