update plugin and use schema version 1.7

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -298,27 +298,32 @@ jobs:
           docker run --rm \
             --env-file tmp/temporal.env \
             temporalio/admin-tools:1.27.2-tctl-1.18 \
-            temporal-sql-tool --plugin postgres \
+            temporal-sql-tool --plugin postgres12 \
               --ep "$POSTGRES_SEEDS:$DB_PORT" \
               --db "$DBNAME" \
               --user "$POSTGRES_USER" \
               --password "$POSTGRES_PWD" \
               --tls \
-              --tls-enable-host-verification=false \
-              validate-schema-version || {
-            echo "Schema not found, setting up"
-            docker run --rm \
-              --env-file tmp/temporal.env \
-              temporalio/admin-tools:1.27.2-tctl-1.18 \
-              temporal-sql-tool --plugin postgres \
-                --ep "$POSTGRES_SEEDS:$DB_PORT" \
-                --db "$DBNAME" \
-                --user "$POSTGRES_USER" \
-                --password "$POSTGRES_PWD" \
-                --tls \
-                --tls-enable-host-verification=false \
-                setup-schema -v 0.0
-          }
+              --tls-disable-host-verification \
+              update-schema -v 1.7 \
+              --dry-run \
+              --schema-dir /etc/temporal/schema/postgresql/v12/temporal \
+            && echo "Schema is already initialized" \
+            || (
+              echo "Schema not found or mismatched. Running setup-schema -v 0.0"
+
+              docker run --rm \
+                --env-file tmp/temporal.env \
+                temporalio/admin-tools:1.27.2-tctl-1.18 \
+                temporal-sql-tool --plugin postgres12 \
+                  --ep "$POSTGRES_SEEDS:$DB_PORT" \
+                  --db "$DBNAME" \
+                  --user "$POSTGRES_USER" \
+                  --password "$POSTGRES_PWD" \
+                  --tls \
+                  --tls-disable-host-verification \
+                  setup-schema -v 0.0
+            )
 
       - name: Deploy to DigitalOcean
         if: inputs.hosting_provider == 'DIGITAL_OCEAN'
